# Generated by Django 4.1.2 on 2022-10-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_brand_carmodel_dealercenter_alter_car_dc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="dc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.dealercenter",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Модель"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="dealercenter",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Адрес"
            ),
        ),
    ]
