# Generated by Django 4.1.2 on 2022-10-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_car_instance_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.brand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.carmodel",
                verbose_name="Модель",
            ),
        ),
    ]
