# Generated by Django 4.1.2 on 2022-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_car_brand_alter_car_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="integration_url",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="integration_url"
            ),
        ),
    ]
