# Generated by Django 4.1.2 on 2022-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("main", "0006_car_integration_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photos",
            field=models.ManyToManyField(
                blank=True, to="gallery.carimage", verbose_name="Фотки"
            ),
        ),
    ]
