version: "3"

services:
  app:
    command: >
      sh -c "poetry run python backend/cars/manage.py migrate &&
             poetry run python backend/cars/manage.py runscript main &&
             poetry run python backend/cars/manage.py runserver 0.0.0.0:8000"
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
     
  celery:
    # restart: always
    build: .
    command: >
      sh -c "cd /app/backend/cars;
            poetry run python -m celery -A core worker -l info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - app

  celery_beat:
    # restart: always
    build: .
    command: >
      sh -c "cd /app/backend/cars; poetry run python -m celery -A core beat -l INFO"
    volumes:
      - .:/app
    depends_on:
      - redis
      - app