# Generated by Django 4.1.2 on 2022-10-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0002_datahub"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integration.datahub",
            ),
        ),
    ]
